import pygame

tile_images = {
    0 : pygame.image.load("sprites/debug.png"),
    1 : pygame.image.load("sprites_grey/gate_left_g.png"),
    2 : pygame.image.load("sprites_grey/gate_mid_g.png"),
    3 : pygame.image.load("sprites_grey/gate_right_g.png"),
    4 : pygame.image.load("sprites_grey/grass_g.png"),
    5 : pygame.image.load("sprites_grey/grass_leaves_g.png"),
    6 : pygame.image.load("sprites_grey/grass_leaves0_g.png"),
    7 : pygame.image.load("sprites_grey/grass_leaves2_g.png"),
    8 : pygame.image.load("sprites_grey/path_bot_grass_g.png"),
    9 : pygame.image.load("sprites_grey/path_corner_bot_left_g.png"),
    10 : pygame.image.load("sprites_grey/path_corner_bot_right_g.png"),
    11 : pygame.image.load("sprites_grey/path_corner_top_left_g.png"),
    12 : pygame.image.load("sprites_grey/path_corner_top_right_g.png"),
    13 : pygame.image.load("sprites_grey/path_g.png"),
    14 : pygame.image.load("sprites_grey/path_left_grass_g.png"),
    15 : pygame.image.load("sprites_grey/path_right_grass_g.png"),
    16 : pygame.image.load("sprites_grey/path_top_grass_g.png"),
    17 : pygame.image.load("sprites_grey/quackers_g.png"),
    18 : pygame.image.load("sprites_grey/sand_bot_left_g.png"),
    19 : pygame.image.load("sprites_grey/sand_bot_right_g.png"),
    20 : pygame.image.load("sprites_grey/sand_g.png"),
    21 : pygame.image.load("sprites_grey/sand_top_left_g.png"),
    22 : pygame.image.load("sprites_grey/sand_top_right_g.png"),
    23 : pygame.image.load("sprites_grey/water_bot_g.png"),
    24 : pygame.image.load("sprites_grey/water_bot_left_g.png"),
    25 : pygame.image.load("sprites_grey/water_bot_right_g.png"),
    26 : pygame.image.load("sprites_grey/water_g.png"),
    27 : pygame.image.load("sprites_grey/water_left_g.png"),
    28 : pygame.image.load("sprites_grey/water_right_g.png"),
    29 : pygame.image.load("sprites_grey/water_top_g.png"),
    30 : pygame.image.load("sprites_grey/water_top_left_g.png"),
    31 : pygame.image.load("sprites_grey/water_top_right_g.png"),
}