import pygame

tile_images = {
    0 :  "sprites/debug.png" ,
    1 :  "sprites/path.png" ,
    2 :  "sprites/path_left_grass.png" ,
    3 :  "sprites/path_right_grass.png" ,
    4 :  "sprites/path_corner_bot_left.png" ,
    5 :  "sprites/path_corner_top_left.png" ,
    6 :  "sprites/path_corner_top_right.png" ,
    7 :  "sprites/path_corner_bot_right.png" ,
    8 :  "sprites/wall.png" ,
    9 :  "sprites/wall_left.png" ,
    10 :  "sprites/wall_right.png" ,
    11 :  "sprites/path_bot_grass.png" ,
    12 :  "sprites/path_top_grass.png" ,
    13 :  "sprites/grass.png" ,
    14 :  "sprites/grass_leaves0.png" ,
    15 :  "sprites/grass_leaves2.png" ,
    16 :  "sprites/water.png" ,
    17 :  "sprites/water_top_right.png" ,
    18 :  "sprites/water_bot_right.png" ,
    19 :  "sprites/water_bot_left.png" ,
    20 :  "sprites/water_top_left.png" ,
    21 :  "sprites/water_top.png" ,
    22 :  "sprites/water_right.png" ,
    23 :  "sprites/water_bot.png" ,
    24 :  "sprites/water_left.png" ,
    25 :  "sprites/quackers.png" ,
    26 :  "sprites/sand.png" ,
    27 :  "sprites/sand_top_left.png" ,
    28 :  "sprites/sand_bot_left.png" ,
    29 :  "sprites/sand_bot_right.png" ,
    30 :  "sprites/sand_top_right.png" ,
    31 :  "sprites/gate_left.png" ,
    32 :  "sprites/gate_mid.png" ,
    33 :  "sprites/gate_right.png" ,
    34 :  "sprites/grass_leaves0.png" ,
}
